### ISSUE TITLE
你好大佬，我在用你的自动学习脚本时遇到了问题。

### ISSUE THREAD

**Issue by KyoMio** [qiurenbo/auto-learing#2]
使用exe文件运行的时候，在读取完当前学习进度以后就自动关闭了。

以下是日志文件内容
[{'domain': 'zy.jxkp.net', 'value': 'CfDJ8FnPfK_Vpe5Ikeq542fg2ZqDW0piGjD8EboXblXVtiWTde8BV11nrIJD2jszkLPnr8Gb-WJXdHJkLb14Nhv693pqS0yAbbq3XS10v1AwJYl1lrfDrsNrnX6L9AFWdlWQfwXX9qqfLGojpsTS3zjIJsM', 'secure': False, 'name': '.AspNetCore.Antiforgery.lX85Zg-o7sY', 'httpOnly': True, 'path': '/'}, {'domain': 'zy.jxkp.net', 'value': 'CfDJ8FnPfK%2FVpe5Ikeq542fg2Zr8N%2FdAGPFI6rlNh88qRt0QcaE6W5X8IwSXXh947p150XD%2BYkL6vC6jxpzJTVqQjvAALvTln%2BKwaomLquss518O7QBUqnVHGzCrW7j3bo8sPIr3JvejpOHRmoRsB%2FzDAtJ5MQD7wOnX%2FfZI%2BiqRgaEB', 'secure': False, 'name': '.AspNetCore.Session', 'httpOnly': True, 'path': '/'}, {'domain': '.jxkp.net', 'value': '176652559c6926-034092cb644e0b-7e40320a-75300-176652559d0555', 'expiry': 1623739515, 'secure': False, 'name': 'UM_distinctid', 'httpOnly': False, 'path': '/'}, {'domain': 'zy.jxkp.net', 'value': '160003667-1608014227-%7C1608014227', 'expiry': 1623739515, 'secure': False, 'name': 'CNZZDATA1256061422', 'httpOnly': False, 'path': '/'}]
Daddy, I find the image path is:auth_code/20201215144516_auth_code.png
Daddy, I know these words:083A
Daddy, I login successfully :)
[['信息管理与知识管理', '14', '335', '18', '未完成', '未参加', <selenium.webdriver.remote.webelement.WebElement (session="74b66dac7504c3426ed42df78ae8e62d", element="0.5129591086889329-11")>], ['战略性新兴产业的困惑和对策', '0', '197', '18', '未完成', '未参加', <selenium.webdriver.remote.webelement.WebElement (session="74b66dac7504c3426ed42df78ae8e62d", element="0.5129591086889329-18")>]]

请问可能是什么问题，我已经尝试添加了chromedrive的环境变量，但是好像不是这个问题，没能解决。

**Comment by DeckardCainCN** [comment]
检查一下 代码里的逻辑
